services:
  backend:
    build: backend
    depends_on:
      - mariadb-database
    environment:
      - MARIADB_PORT=3306
      - MARIADB_HOST=mariadb-database
      - MARIADB_DATABASE=example
      - MARIADB_PASSWORD=password123
    ports:
      - "8081:8000"
  mariadb-database:
    image: mariadb:10.5.12
    restart: always
    volumes:
      - db-data-2:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=example
      - MARIADB_ROOT_PASSWORD=password123
volumes:
  db-data-2:
